/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2023-04-14 07:24:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.card;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Single+Day&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- reset -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- fontawesome css: https://fontawesome.com -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/assets/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/assets/css/list.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-title-wrapper\">\r\n");
      out.write("            <h1 class=\"main-title\">꾸러기 게시판</h1>\r\n");
      out.write("            <button class=\"add-btn\">새 글 쓰기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-container\">\r\n");
      out.write("            <div class=\"card-wrapper\">\r\n");
      out.write("                <section class=\"card\">\r\n");
      out.write("                    <div class=\"card-title-wrapper\">\r\n");
      out.write("                        <h2 class=\"card-title\">너 머냐공~~</h2>\r\n");
      out.write("                        <div class=\"time-view-wrapper\">\r\n");
      out.write("                            <div class=\"time\"><i class=\"far fa-clock\"></i>2023-04-14 12:50</div>\r\n");
      out.write("                            <div class=\"view\">\r\n");
      out.write("                                <i class=\"fas fa-eye\"></i>\r\n");
      out.write("                                <span class=\"view-count\">15</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            abcsdfjklaskfjdklasjfldjsafldlajfsf\r\n");
      out.write("                            sdjflaksjfdlksajflsakjflsdakjfjaskldf\r\n");
      out.write("                            sljdkfsajlfdsjflksjlfksdajflskdajfdsakl\r\n");
      out.write("                            sdjflsajflksdajfflsajfldsjflsjalfdjsaflk\r\n");
      out.write("                            sajdflksajfdlsajflsdjlfkjslfjdafsjdlk\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <div class=\"card-btn-group\">\r\n");
      out.write("                    <button class=\"del-btn\">\r\n");
      out.write("                        <i class=\"fas fa-times\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-wrapper\">\r\n");
      out.write("                <section class=\"card\">\r\n");
      out.write("                    <div class=\"card-title-wrapper\">\r\n");
      out.write("                        <h2 class=\"card-title\">너 머냐공~~</h2>\r\n");
      out.write("                        <div class=\"time-view-wrapper\">\r\n");
      out.write("                            <div class=\"time\"><i class=\"far fa-clock\"></i>2023-04-14 12:50</div>\r\n");
      out.write("                            <div class=\"view\">\r\n");
      out.write("                                <i class=\"fas fa-eye\"></i>\r\n");
      out.write("                                <span class=\"view-count\">15</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            abcsdfjklaskfjdklasjfldjsafldlajfsf\r\n");
      out.write("                            sdjflaksjfdlksajflsakjflsdakjfjaskldf\r\n");
      out.write("                            sljdkfsajlfdsjflksjlfksdajflskdajfdsakl\r\n");
      out.write("                            sdjflsajflksdajfflsajfldsjflsjalfdjsaflk\r\n");
      out.write("                            sajdflksajfdlsajflsdjlfkjslfjdafsjdlk\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <div class=\"card-btn-group\">\r\n");
      out.write("                    <button class=\"del-btn\">\r\n");
      out.write("                        <i class=\"fas fa-times\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-wrapper\">\r\n");
      out.write("                <section class=\"card\">\r\n");
      out.write("                    <div class=\"card-title-wrapper\">\r\n");
      out.write("                        <h2 class=\"card-title\">너 머냐공~~</h2>\r\n");
      out.write("                        <div class=\"time-view-wrapper\">\r\n");
      out.write("                            <div class=\"time\"><i class=\"far fa-clock\"></i>2023-04-14 12:50</div>\r\n");
      out.write("                            <div class=\"view\">\r\n");
      out.write("                                <i class=\"fas fa-eye\"></i>\r\n");
      out.write("                                <span class=\"view-count\">15</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            abcsdfjklaskfjdklasjfldjsafldlajfsf\r\n");
      out.write("                            sdjflaksjfdlksajflsakjflsdakjfjaskldf\r\n");
      out.write("                            sljdkfsajlfdsjflksjlfksdajflskdajfdsakl\r\n");
      out.write("                            sdjflsajflksdajfflsajfldsjflsjalfdjsaflk\r\n");
      out.write("                            sajdflksajfdlsajflsdjlfkjslfjdafsjdlk\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <div class=\"card-btn-group\">\r\n");
      out.write("                    <button class=\"del-btn\">\r\n");
      out.write("                        <i class=\"fas fa-times\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function removeDown(e) {\r\n");
      out.write("            if (!e.target.matches('.card-container *')) return;\r\n");
      out.write("            const $targetCard = e.target.closest('.card-wrapper');\r\n");
      out.write("            $targetCard?.removeAttribute('id', 'card-down');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function removeHover(e) {\r\n");
      out.write("            if (!e.target.matches('.card-container *')) return;\r\n");
      out.write("            const $targetCard = e.target.closest('.card');\r\n");
      out.write("            $targetCard?.classList.remove('card-hover');\r\n");
      out.write("\r\n");
      out.write("            const $delBtn = e.target.closest('.card-wrapper')?.querySelector('.del-btn');\r\n");
      out.write("            $delBtn.style.opacity = '0';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const $cardContainer = document.querySelector('.card-container');\r\n");
      out.write("\r\n");
      out.write("        $cardContainer.onmouseover = e => {\r\n");
      out.write("\r\n");
      out.write("            if (!e.target.matches('.card-container *')) return;\r\n");
      out.write("\r\n");
      out.write("            const $targetCard = e.target.closest('.card');\r\n");
      out.write("            $targetCard?.classList.add('card-hover');\r\n");
      out.write("\r\n");
      out.write("            const $delBtn = e.target.closest('.card-wrapper')?.querySelector('.del-btn');\r\n");
      out.write("            $delBtn.style.opacity = '1';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $cardContainer.onmousedown = e => {\r\n");
      out.write("\r\n");
      out.write("            if (!e.target.matches('.card-container *')) return;\r\n");
      out.write("\r\n");
      out.write("            const $targetCard = e.target.closest('.card-wrapper');\r\n");
      out.write("            $targetCard?.setAttribute('id', 'card-down');\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        $cardContainer.onmouseup = removeDown;\r\n");
      out.write("\r\n");
      out.write("        $cardContainer.addEventListener('mouseout', removeDown);\r\n");
      out.write("        $cardContainer.addEventListener('mouseout', removeHover);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
